apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nacos-server
  name: nacos-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-server
  template:
    metadata:
      labels:
        app: nacos-server
    spec:
      containers:
      - image: nacos/nacos-server:2.0.2
        imagePullPolicy: Always
        name: nacos-server
        ports:
        - containerPort: 8848
          protocol: TCP
        - containerPort: 9848
          protocol: TCP
        securityContext:
          privileged: true  # 可能需要
        env:
        - name: MODE
          value: standalone
        - name: PREFER_HOST_MODE
          value: hostname
        - name: NACOS_AUTH_ENABLE
          value: "false"
        - name: TIME_ZONE
          value: Asia/Shanghai
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
