apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nacos-server
spec:
  rules:
  - host: nacos.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nacos-server
            port:
              number: 8848