apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-svc
spec:
  ports:
    - name: port-80
      port: 80
      protocol: TCP
      targetPort: 19999
  selector:
    app: zuul-gateway
  sessionAffinity: None
  type: ClusterIP
